### ISSUE TITLE
Unable to install dependencies for server

### ISSUE THREAD

**Issue by pentagramz** [OWASP/igoat#21]
Unable to install dependencies for server

pfa screenshots
![screen shot 2017-07-17 at 10 56 08 pm](https://user-images.githubusercontent.com/7072014/28281066-78a59d7a-6b43-11e7-9b82-dceba8dbb57b.png)
![screen shot 2017-07-17 at 10 55 10 pm](https://user-images.githubusercontent.com/7072014/28281067-78ac8b6c-6b43-11e7-90d7-6a78fb9a6c6d.png)

**Comment by swaroopsy** [comment]
Thanks @pentagramz for raising this. However as you can see in error message, you'll require ruby >= 2.2.2. Upgrading ruby should solve this issue. Its working properly on ruby version 2.4.0. If you get any issues on latest ruby version, please raise new issue.
![1](https://user-images.githubusercontent.com/9929997/28451129-23e43044-6e09-11e7-93d0-7e473a423787.png)

**Comment by swaroopsy** [comment]
+Added docker support. No need to setup server manually.

**Comment by pentagramz** [comment]
![screen shot 2018-04-28 at 7 55 34 pm](https://user-images.githubusercontent.com/7072014/39397530-6d065660-4b1e-11e8-879c-50ef4986d0b7.png)

**Comment by pentagramz** [comment]
just marking as this solved the issue thanks
