### ISSUE TITLE
reverse engineering

### ISSUE THREAD

**Issue by pentagramz** [OWASP/igoat#54]
reverse engineering string not found in hopper?
any pointers
![screen shot 2018-06-14 at 11 06 51 pm](https://user-images.githubusercontent.com/7072014/41428496-e5ef48f6-7027-11e8-9061-2315865842e2.png)

**Comment by pentagramz** [comment]
mach-0 armv7 not seen in selection of hopper

**Comment by swaroopsecurity** [comment]
Hi @pentagramz it's working all fine. PFA. Closing this ticket.
<img width="891" alt="igoat_hopper" src="https://user-images.githubusercontent.com/33461919/41462846-d741c5f6-70b1-11e8-9261-9a3b8f686a02.png">

**Comment by swaroopsy** [comment]
@pentagramz It's working all fine. PFA.
<img width="891" alt="igoat_hopper" src="https://user-images.githubusercontent.com/9929997/41462890-03d67cd8-70b2-11e8-9a31-4b3f2126036f.png">

**Comment by pentagramz** [comment]
are u using the same ipa seen in github?
