### ISSUE TITLE
iGoat Installable IPA

### ISSUE THREAD

**Issue by umang1226** [OWASP/igoat#9]
Can you please provide with an installable IPA file of the latest version of iGoat application.

**Comment by swaroopsy** [comment]
Hi Umag,

We've got this requirement from many other users as well. We'll soon add ipa to this Github project. Thanks.

**Comment by swaroopsy** [comment]
Hi Umang,

You can now find attached .ipa file with project. You can also download it from https://github.com/OWASP/igoat/blob/master/iGoat_v.3.0.ipa. Closing the issue.

**Comment by umang1226** [comment]
Thank you for the update. It will be really helpful.

Thanks,
Umang Chavda
